language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
    #  - jruby
    #- jruby-head
  - rbx-2.2.10
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
install:
    #- sudo apt-get update && sudo apt-get install --force-yes socat
script:
  - bundle install
  - bundle exec rspec -fd
